### ISSUE TITLE
Challenge +health% Incorrect

### ISSUE THREAD

**Issue by duckfin** [Grimy/Grimy.github.io#3] opened 2017-01-13 22:23 UTC
Hey there. Imported save, and the advanced options show I've got +1158% enemy health in maps... which I don't. Currently running the 2017-01-11 daily challenge: +240% health, and +270% health in maps. Maybe this is an issue with it combining the two values?

**Comment by Grimy** [comment] 2017-01-16 21:23
Not a bug. The two modifiers stack multiplicatively:
+240% = 3.4 multiplier
+270% = 3.7 multiplier
3.4 x 3.7 = 12.58 multiplier = +1158%

**Comment by Grimy** [comment] 2017-01-19 15:07
I’m closing this issue, but leaving the comments open in case you have something to add.

**Closed as completed by Grimy** 2017-01-19 15:07 UTC
