### ISSUE TITLE
z400+ switching bug

### ISSUE THREAD

**Issue by SpiderScripts** [Grimy/Grimy.github.io#10] opened 2017-03-17 17:09 UTC
Currently, when you switch to z400+ it adjusts a couple of the advanced options.

When you then switch back to any of the other presets, it leaves those advanced options in place, which obviously produces completely different perk suggestions.

Obviously you don't want the advanced settings to be reset every time you change the presets dropdown, but those specific settings the z400+ impacts could be reset when you switch out of z400+, on the condition that they also haven't been changed...

Edit: just realised this had already been reported, and after testing those advanced settings aren't actually what breaks the suggestions...

**Comment by Grimy** [comment] 2017-03-17 17:21
This is a duplicate of #7, that I just fixed. 

However, it sounds like you had another issue as well. What do you mean by breaking the suggestions? Did Perky recommend a particularly bad perk distribution?

**Comment by SpiderScripts** [comment] 2017-03-18 19:40
The advanced settings do now reset themselves properly, but for some reason the suggestions don't return to what they were before.

For example, with my current save export, on the broken planet preset it is recommending 20 coordinated.  If I switch to z400+ then is recommends a setup with 22 coordinated.

Now when I switch back to broken planet, it is still recommending a setup with 22 coordinated, although different from the z400+ suggestion.

**Comment by Grimy** [comment] 2017-03-19 08:54
Thanks for the details! This is now fixed as well.

**Closed as completed** 2017-03-19 08:54 UTC
